"""empty message

Revision ID: 39d862fcdbd1
Revises: 9482407b4898
Create Date: 2022-05-31 18:04:23.554264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39d862fcdbd1'
down_revision = '9482407b4898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('img', sa.String(length=2083), nullable=True))
    op.add_column('events', sa.Column('type', sa.String(), nullable=True))
    op.create_foreign_key(None, 'events', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'type')
    op.drop_column('events', 'img')
    # ### end Alembic commands ###
