"""Initial Migration

Revision ID: 9482407b4898
Revises: 
Create Date: 2022-05-31 17:45:11.326990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9482407b4898'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('img', sa.String(length=2083), nullable=True))
    op.add_column('events', sa.Column('type', sa.String(), nullable=True))
    op.create_foreign_key(None, 'events', 'locations', ['location_id'], ['id'])
    op.alter_column('payments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_column('events', 'type')
    op.drop_column('events', 'img')
    # ### end Alembic commands ###
